/usr/bin/touch /var/lib/texmf/postinstall/texlive-collection-bibtexextra_rm.lsr
/usr/libexec/update_tlpdb remove \
aichej \
ajl \
amsrefs \
apacite \
apalike2 \
archaeologie \
beebe \
besjournals \
bestpapers \
bibarts \
biber.i386-cygwin \
biber \
biber.x86_64-cygwin \
bibexport.i386-cygwin \
bibexport \
bibexport.x86_64-cygwin \
bibhtml \
biblatex-abnt \
biblatex-anonymous \
biblatex-apa \
biblatex-bookinarticle \
biblatex-bookinother \
biblatex-bwl \
biblatex-caspervector \
biblatex-chem \
biblatex-chicago \
biblatex-dw \
biblatex-fiwi \
biblatex-gost \
biblatex-historian \
biblatex-ieee \
biblatex-iso690 \
biblatex-juradiss \
biblatex-luh-ipw \
biblatex-manuscripts-philology \
biblatex-mla \
biblatex-morenames \
biblatex-multiple-dm \
biblatex-musuos \
biblatex-nature \
biblatex-nejm \
biblatex-opcit-booktitle \
biblatex-philosophy \
biblatex-phys \
biblatex-publist \
biblatex-realauthor \
biblatex-science \
biblatex-source-division \
biblatex-subseries \
biblatex-swiss-legal \
biblatex-trad \
biblatex-true-citepages-omit \
biblatex \
biblist \
bibtexperllibs \
bibtopic \
bibtopicprefix \
bibunits \
bookdb \
breakcites \
cell \
chbibref \
chembst \
chicago-annote \
chicago \
chscite \
citeall \
collection-bibtexextra \
collref \
compactbib \
crossrefware.i386-cygwin \
crossrefware \
crossrefware.x86_64-cygwin \
custom-bib \
din1505 \
dk-bib \
doipubmed \
ecobiblatex \
economic \
fbs \
figbib \
footbib \
francais-bst \
geschichtsfrkl \
harvard \
harvmac \
historische-zeitschrift \
ijqc \
inlinebib \
iopart-num \
jneurosci \
jurabib \
ksfh_nat \
listbib.i386-cygwin \
listbib \
listbib.x86_64-cygwin \
logreq \
margbib \
multibib \
multibibliography.i386-cygwin \
multibibliography \
multibibliography.x86_64-cygwin \
munich \
nar \
nmbib \
notes2bib \
oscola \
perception \
pnas2009 \
rsc \
showtags \
sort-by-letters \
splitbib \
turabian-formatting \
uni-wtal-ger \
uni-wtal-lin \
urlbst.i386-cygwin \
urlbst \
urlbst.x86_64-cygwin \
usebib \
vak \
xcite \

